version: '3.8'

services:
  kong-database:
    image: postgres:13
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
    ports:
      - "5432:5432"
    volumes:
      - kong-database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      timeout: 5s
      retries: 5

  kong-migrations:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
    depends_on:
      kong-database:
        condition: service_healthy
    command: >
      sh -c "
      kong migrations bootstrap &&
      kong migrations up &&
      kong migrations finish &&
      touch /tmp/migrations_complete &&
      tail -f /dev/null
      "
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/migrations_complete"]
      interval: 10s
      timeout: 10s
      retries: 10

  kong:
    image: kong:latest
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml  # Use declarative config
    ports:
      - "8000:8000" # Kong proxy
      - "8443:8443"
      - "8001:8001" # Kong admin API
      - "8444:8444"
    depends_on:
      kong-migrations:
        condition: service_healthy
    volumes:
      - ./gateway/kong.yml:/usr/local/kong/declarative/kong.yml  # Mount your kong.yml file

  employee-microservice:
    build: ./employee-microservice
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongo:27017/employee-db

  leave-microservice:
    build: ./leave-microservice
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongo:27017/leave-db

  frontend:
    build: ./frontend  # Assuming the Dockerfile is in the 'frontend' directory
    ports:
      - "2000:2000"  # Expose the frontend on port 2000
    environment:
      NEXT_PUBLIC_API_URL: http://kong:8000  # Use Kong's proxy for API calls
    depends_on:
      - kong  # Wait for Kong to be ready

  mongo: # MongoDB service
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  kong-database:
  mongo-data:
